import React from 'react'
import {Row, Col, Card} from 'antd'
import D3SimpleForceChart from '../components/charts/D3SimpleForceChart'

class SimpleForceChart2 extends React.Component {
    render() {
        const data = {
            nodes: [
                {name: "Group5-35365327", type: "4"},
                {name: "Group1-226243718", type: "0"},
                {name: "Group5-119801456", type: "4"},
                {name: "Group4-643873396", type: "3"},
                {name: "Group9-7349", type: "8"},
                {name: "Group2-691415738", type: "1"},
                {name: "Group12-11870568", type: "11"},
                {name: "Group2-31012715", type: "1"},
                {name: "Group1-14583962", type: "0"},
                {name: "Group4-63231", type: "3"},
                {name: "Group1-404216060", type: "0"},
                {name: "Group9-35989160", type: "8"},
                {name: "Group6-1372433", type: "5"},
                {name: "Group1-253350665", type: "0"},
                {name: "Group2-40966108", type: "1"},
                {name: "Group2-106017013", type: "1"},
                {name: "Group9-344849038", type: "8"},
                {name: "Group9-35359510", type: "8"},
                {name: "Group1-35847683", type: "0"},
                {name: "Group3-23079060", type: "2"},
                {name: "Group1-54992199", type: "0"},
                {name: "Group1-32820037", type: "0"},
                {name: "Group1-387783803", type: "0"},
                {name: "Group9-208259", type: "8"},
                {name: "Group9-90920075", type: "8"},
                {name: "Group2-28626598", type: "1"},
                {name: "Group9-367877", type: "8"},
                {name: "Group9-730732", type: "8"},
                {name: "Group1-36267054", type: "0"},
                {name: "Group1-473524263", type: "0"},
                {name: "Group2-423738152", type: "1"},
                {name: "Group1-1519547765", type: "0"},
                {name: "Group7-49746395", type: "6"},
                {name: "Group8-79577853", type: "7"},
                {name: "Group1-393166851", type: "0"},
                {name: "Group7-27218150", type: "6"},
                {name: "Group1-38053181", type: "0"},
                {name: "Group2-2306780", type: "1"},
                {name: "Group2-625647470", type: "1"},
                {name: "Group12-3433092", type: "11"},
                {name: "Group2-37090048", type: "1"},
                {name: "Group9-458165375", type: "8"},
                {name: "Group9-11646119", type: "8"},
                {name: "Group1-3530725", type: "0"},
                {name: "Group2-562197", type: "1"},
                {name: "Group12-491461718", type: "11"},
                {name: "Group2-434376696", type: "1"},
                {name: "Group5-12566101", type: "4"},
                {name: "Group2-276928941", type: "1"},
                {name: "Group1-303740257", type: "0"},
                {name: "Group1-37663924", type: "0"},
                {name: "Group7-194484313", type: "6"},
                {name: "Group9-316568752", type: "8"},
                {name: "Group5-32708626", type: "4"},
                {name: "Group12-517491339", type: "11"},
                {name: "Group10-18343098", type: "9"},
                {name: "Group12-617285", type: "11"},
                {name: "Group12-203680252", type: "11"},
                {name: "Group10-5294454", type: "9"},
                {name: "Group1-946974", type: "0"},
                {name: "Group5-424658638", type: "4"},
                {name: "Group1-403449453", type: "0"},
                {name: "Group3-486287787", type: "2"},
                {name: "Group5-487640933", type: "4"},
                {name: "Group1-394205865", type: "0"},
                {name: "Group1-52165725", type: "0"},
                {name: "Group1-4474705", type: "0"},
                {name: "Group1-540564177", type: "0"},
                {name: "Group5-7487399", type: "4"},
                {name: "Group2-7552204", type: "1"},
                {name: "Group1-447317111", type: "0"},
                {name: "Group2-11100920", type: "1"},
                {name: "Group1-4029133", type: "0"},
                {name: "Group2-125526", type: "1"},
                {name: "Group9-8049684", type: "8"},
                {name: "Group3-14871346", type: "2"},
                {name: "Group2-17171565", type: "1"},
                {name: "Group1-470156882", type: "0"},
                {name: "Group1-9458053", type: "0"},
                {name: "Group1-25637408", type: "0"},
                {name: "Group1-14804670", type: "0"},
                {name: "Group1-942755", type: "0"},
                {name: "Group2-254463269", type: "1"},
                {name: "Group1-170948267", type: "0"},
                {name: "Group9-90361813", type: "8"},
                {name: "Group2-235555226", type: "1"},
                {name: "Group2-8096990", type: "1"},
                {name: "Group2-1241806378", type: "1"},
                {name: "Group1-598464467", type: "0"},
                {name: "Group2-174501086", type: "1"},
                {name: "Group9-417583826", type: "8"},
                {name: "Group1-1958342", type: "0"},
                {name: "Group4-32708543", type: "3"},
                {name: "Group2-25876945", type: "1"},
                {name: "Group6-81824112", type: "5"},
                {name: "Group2-23947287", type: "1"},
                {name: "Group1-49246269", type: "0"},
                {name: "Group2-3957971", type: "1"},
                {name: "Group1-337312411", type: "0"},
                {name: "Group1-397490386", type: "0"},
            ],
            edges: [
                {source: 0, target: 22, relation: 'cross', value: 3},
                {source: 0, target: 43, relation: 'cross', value: 3},
                {source: 0, target: 53, relation: 'within', value: 3},
                {source: 0, target: 71, relation: 'cross', value: 3},
                {source: 0, target: 80, relation: 'cross', value: 3},
                {source: 1, target: 26, relation: 'cross', value: 3},
                {source: 1, target: 41, relation: 'cross', value: 3},
                {source: 1, target: 44, relation: 'cross', value: 3},
                {source: 1, target: 73, relation: 'cross', value: 3},
                {source: 1, target: 99, relation: 'within', value: 3},
                {source: 4, target: 26, relation: 'within', value: 3},
                {source: 4, target: 44, relation: 'cross', value: 3},
                {source: 4, target: 50, relation: 'cross', value: 3},
                {source: 4, target: 56, relation: 'cross', value: 3},
                {source: 4, target: 59, relation: 'cross', value: 3},
                {source: 4, target: 67, relation: 'cross', value: 3},
                {source: 4, target: 68, relation: 'cross', value: 3},
                {source: 4, target: 70, relation: 'cross', value: 3},
                {source: 4, target: 93, relation: 'cross', value: 3},
                {source: 5, target: 42, relation: 'cross', value: 3},
                {source: 5, target: 44, relation: 'within', value: 3},
                {source: 5, target: 50, relation: 'cross', value: 3},
                {source: 5, target: 64, relation: 'cross', value: 3},
                {source: 5, target: 73, relation: 'within', value: 3},
                {source: 5, target: 75, relation: 'cross', value: 3},
                {source: 11, target: 17, relation: 'within', value: 3},
                {source: 11, target: 32, relation: 'cross', value: 3},
                {source: 11, target: 36, relation: 'cross', value: 3},
                {source: 11, target: 37, relation: 'cross', value: 3},
                {source: 11, target: 38, relation: 'cross', value: 3},
                {source: 11, target: 41, relation: 'within', value: 3},
                {source: 11, target: 52, relation: 'within', value: 3},
                {source: 11, target: 54, relation: 'cross', value: 3},
                {source: 11, target: 59, relation: 'cross', value: 3},
                {source: 11, target: 64, relation: 'cross', value: 3},
                {source: 11, target: 80, relation: 'cross', value: 3},
                {source: 11, target: 82, relation: 'cross', value: 3},
                {source: 11, target: 85, relation: 'cross', value: 3},
                {source: 11, target: 88, relation: 'cross', value: 3},
                {source: 11, target: 93, relation: 'cross', value: 3},
                {source: 11, target: 94, relation: 'cross', value: 3},
                {source: 12, target: 6, relation: 'cross', value: 3},
                {source: 12, target: 9, relation: 'cross', value: 3},
                {source: 12, target: 27, relation: 'cross', value: 3},
                {source: 12, target: 82, relation: 'cross', value: 3},
                {source: 12, target: 97, relation: 'cross', value: 3},
                {source: 15, target: 74, relation: 'cross', value: 3},
                {source: 17, target: 9, relation: 'cross', value: 3},
                {source: 17, target: 18, relation: 'cross', value: 3},
                {source: 17, target: 23, relation: 'within', value: 3},
                {source: 17, target: 32, relation: 'cross', value: 3},
                {source: 17, target: 33, relation: 'cross', value: 3},
                {source: 17, target: 44, relation: 'cross', value: 3},
                {source: 17, target: 50, relation: 'cross', value: 3},
                {source: 17, target: 51, relation: 'cross', value: 3},
                {source: 17, target: 59, relation: 'cross', value: 3},
                {source: 17, target: 69, relation: 'cross', value: 3},
                {source: 17, target: 73, relation: 'cross', value: 3},
                {source: 17, target: 77, relation: 'cross', value: 3},
                {source: 17, target: 82, relation: 'cross', value: 3},
                {source: 17, target: 85, relation: 'cross', value: 3},
                {source: 17, target: 90, relation: 'within', value: 3},
                {source: 21, target: 25, relation: 'cross', value: 3},
                {source: 21, target: 28, relation: 'within', value: 3},
                {source: 21, target: 30, relation: 'cross', value: 3},
                {source: 21, target: 83, relation: 'within', value: 3},
                {source: 21, target: 84, relation: 'cross', value: 3},
                {source: 23, target: 10, relation: 'cross', value: 3},
                {source: 23, target: 31, relation: 'cross', value: 3},
                {source: 23, target: 33, relation: 'cross', value: 3},
                {source: 23, target: 42, relation: 'within', value: 3},
                {source: 23, target: 59, relation: 'cross', value: 3},
                {source: 23, target: 75, relation: 'cross', value: 3},
                {source: 23, target: 84, relation: 'within', value: 3},
                {source: 23, target: 93, relation: 'cross', value: 3},
                {source: 23, target: 95, relation: 'cross', value: 3},
                {source: 24, target: 14, relation: 'cross', value: 3},
                {source: 24, target: 18, relation: 'cross', value: 3},
                {source: 24, target: 41, relation: 'within', value: 3},
                {source: 24, target: 46, relation: 'cross', value: 3},
                {source: 24, target: 89, relation: 'cross', value: 3},
                {source: 24, target: 96, relation: 'cross', value: 3},
                {source: 25, target: 6, relation: 'cross', value: 3},
                {source: 25, target: 18, relation: 'cross', value: 3},
                {source: 25, target: 33, relation: 'cross', value: 3},
                {source: 25, target: 36, relation: 'cross', value: 3},
                {source: 25, target: 42, relation: 'cross', value: 3},
                {source: 25, target: 69, relation: 'within', value: 3},
                {source: 25, target: 83, relation: 'cross', value: 3},
                {source: 26, target: 5, relation: 'cross', value: 3},
                {source: 26, target: 73, relation: 'cross', value: 3},
                {source: 26, target: 93, relation: 'cross', value: 3},
                {source: 27, target: 2, relation: 'cross', value: 3},
                {source: 27, target: 4, relation: 'within', value: 3},
                {source: 27, target: 10, relation: 'cross', value: 3},
                {source: 27, target: 12, relation: 'cross', value: 3},
                {source: 27, target: 14, relation: 'cross', value: 3},
                {source: 27, target: 15, relation: 'cross', value: 3},
                {source: 27, target: 36, relation: 'cross', value: 3},
                {source: 27, target: 57, relation: 'cross', value: 3},
                {source: 27, target: 65, relation: 'cross', value: 3},
                {source: 27, target: 73, relation: 'cross', value: 3},
                {source: 27, target: 83, relation: 'cross', value: 3},
                {source: 27, target: 95, relation: 'cross', value: 3},
                {source: 28, target: 12, relation: 'cross', value: 3},
                {source: 28, target: 25, relation: 'cross', value: 3},
                {source: 28, target: 30, relation: 'cross', value: 3},
                {source: 28, target: 32, relation: 'cross', value: 3},
                {source: 28, target: 41, relation: 'cross', value: 3},
                {source: 28, target: 50, relation: 'within', value: 3},
                {source: 28, target: 68, relation: 'cross', value: 3},
                {source: 28, target: 79, relation: 'within', value: 3},
                {source: 28, target: 83, relation: 'within', value: 3},
                {source: 28, target: 88, relation: 'within', value: 3},
                {source: 28, target: 96, relation: 'within', value: 3},
                {source: 28, target: 97, relation: 'cross', value: 3},
                {source: 31, target: 2, relation: 'cross', value: 3},
                {source: 31, target: 18, relation: 'within', value: 3},
                {source: 31, target: 21, relation: 'within', value: 3},
                {source: 31, target: 23, relation: 'cross', value: 3},
                {source: 31, target: 40, relation: 'cross', value: 3},
                {source: 31, target: 49, relation: 'within', value: 3},
                {source: 31, target: 66, relation: 'within', value: 3},
                {source: 31, target: 73, relation: 'cross', value: 3},
                {source: 31, target: 77, relation: 'within', value: 3},
                {source: 31, target: 80, relation: 'within', value: 3},
                {source: 31, target: 83, relation: 'within', value: 3},
                {source: 31, target: 95, relation: 'cross', value: 3},
                {source: 34, target: 6, relation: 'cross', value: 3},
                {source: 34, target: 10, relation: 'within', value: 3},
                {source: 34, target: 21, relation: 'within', value: 3},
                {source: 34, target: 22, relation: 'within', value: 3},
                {source: 34, target: 23, relation: 'cross', value: 3},
                {source: 34, target: 29, relation: 'within', value: 3},
                {source: 34, target: 36, relation: 'within', value: 3},
                {source: 34, target: 39, relation: 'cross', value: 3},
                {source: 34, target: 41, relation: 'cross', value: 3},
                {source: 34, target: 45, relation: 'cross', value: 3},
                {source: 34, target: 50, relation: 'within', value: 3},
                {source: 34, target: 54, relation: 'cross', value: 3},
                {source: 34, target: 58, relation: 'cross', value: 3},
                {source: 34, target: 70, relation: 'within', value: 3},
                {source: 34, target: 73, relation: 'cross', value: 3},
                {source: 34, target: 82, relation: 'cross', value: 3},
                {source: 34, target: 83, relation: 'within', value: 3},
                {source: 34, target: 94, relation: 'cross', value: 3},
                {source: 34, target: 95, relation: 'cross', value: 3},
                {source: 36, target: 1, relation: 'within', value: 3},
                {source: 36, target: 6, relation: 'cross', value: 3},
                {source: 36, target: 28, relation: 'within', value: 3},
                {source: 36, target: 48, relation: 'cross', value: 3},
                {source: 36, target: 60, relation: 'cross', value: 3},
                {source: 36, target: 83, relation: 'within', value: 3},
                {source: 36, target: 90, relation: 'cross', value: 3},
                {source: 37, target: 0, relation: 'cross', value: 3},
                {source: 37, target: 38, relation: 'within', value: 3},
                {source: 37, target: 69, relation: 'within', value: 3},
                {source: 37, target: 89, relation: 'within', value: 3},
                {source: 38, target: 33, relation: 'cross', value: 3},
                {source: 38, target: 40, relation: 'within', value: 3},
                {source: 38, target: 83, relation: 'cross', value: 3},
                {source: 40, target: 33, relation: 'cross', value: 3},
                {source: 40, target: 59, relation: 'cross', value: 3},
                {source: 40, target: 68, relation: 'cross', value: 3},
                {source: 41, target: 8, relation: 'cross', value: 3},
                {source: 41, target: 25, relation: 'cross', value: 3},
                {source: 41, target: 32, relation: 'cross', value: 3},
                {source: 41, target: 33, relation: 'cross', value: 3},
                {source: 41, target: 42, relation: 'within', value: 3},
                {source: 41, target: 50, relation: 'cross', value: 3},
                {source: 41, target: 65, relation: 'cross', value: 3},
                {source: 41, target: 94, relation: 'cross', value: 3},
                {source: 45, target: 40, relation: 'cross', value: 3},
                {source: 50, target: 18, relation: 'within', value: 3},
                {source: 50, target: 28, relation: 'within', value: 3},
                {source: 50, target: 30, relation: 'cross', value: 3},
                {source: 50, target: 44, relation: 'cross', value: 3},
                {source: 50, target: 74, relation: 'cross', value: 3},
                {source: 50, target: 79, relation: 'within', value: 3},
                {source: 52, target: 20, relation: 'cross', value: 3},
                {source: 52, target: 24, relation: 'within', value: 3},
                {source: 52, target: 62, relation: 'cross', value: 3},
                {source: 52, target: 82, relation: 'cross', value: 3},
                {source: 52, target: 99, relation: 'cross', value: 3},
                {source: 53, target: 68, relation: 'within', value: 3},
                {source: 53, target: 86, relation: 'cross', value: 3},
                {source: 54, target: 64, relation: 'cross', value: 3},
                {source: 54, target: 89, relation: 'cross', value: 3},
                {source: 56, target: 70, relation: 'cross', value: 3},
                {source: 59, target: 5, relation: 'cross', value: 3},
                {source: 59, target: 19, relation: 'cross', value: 3},
                {source: 59, target: 25, relation: 'cross', value: 3},
                {source: 59, target: 26, relation: 'cross', value: 3},
                {source: 59, target: 30, relation: 'cross', value: 3},
                {source: 59, target: 33, relation: 'cross', value: 3},
                {source: 59, target: 70, relation: 'within', value: 3},
                {source: 59, target: 71, relation: 'cross', value: 3},
                {source: 59, target: 83, relation: 'within', value: 3},
                {source: 59, target: 96, relation: 'within', value: 3},
                {source: 59, target: 98, relation: 'within', value: 3},
                {source: 64, target: 5, relation: 'cross', value: 3},
                {source: 64, target: 19, relation: 'cross', value: 3},
                {source: 64, target: 47, relation: 'cross', value: 3},
                {source: 65, target: 9, relation: 'cross', value: 3},
                {source: 65, target: 16, relation: 'cross', value: 3},
                {source: 65, target: 30, relation: 'cross', value: 3},
                {source: 65, target: 42, relation: 'cross', value: 3},
                {source: 65, target: 83, relation: 'within', value: 3},
                {source: 68, target: 53, relation: 'within', value: 3},
                {source: 68, target: 60, relation: 'within', value: 3},
                {source: 68, target: 89, relation: 'cross', value: 3},
                {source: 68, target: 96, relation: 'cross', value: 3},
                {source: 70, target: 12, relation: 'cross', value: 3},
                {source: 70, target: 18, relation: 'within', value: 3},
                {source: 70, target: 29, relation: 'within', value: 3},
                {source: 70, target: 34, relation: 'within', value: 3},
                {source: 70, target: 43, relation: 'within', value: 3},
                {source: 70, target: 44, relation: 'cross', value: 3},
                {source: 70, target: 50, relation: 'within', value: 3},
                {source: 70, target: 59, relation: 'within', value: 3},
                {source: 70, target: 68, relation: 'cross', value: 3},
                {source: 70, target: 85, relation: 'cross', value: 3},
                {source: 70, target: 86, relation: 'cross', value: 3},
                {source: 70, target: 94, relation: 'cross', value: 3},
                {source: 71, target: 0, relation: 'cross', value: 3},
                {source: 71, target: 6, relation: 'cross', value: 3},
                {source: 71, target: 18, relation: 'cross', value: 3},
                {source: 71, target: 46, relation: 'within', value: 3},
                {source: 71, target: 51, relation: 'cross', value: 3},
                {source: 71, target: 58, relation: 'cross', value: 3},
                {source: 71, target: 73, relation: 'within', value: 3},
                {source: 71, target: 89, relation: 'within', value: 3},
                {source: 71, target: 94, relation: 'cross', value: 3},
                {source: 76, target: 8, relation: 'cross', value: 3},
                {source: 76, target: 17, relation: 'cross', value: 3},
                {source: 76, target: 20, relation: 'cross', value: 3},
                {source: 76, target: 35, relation: 'cross', value: 3},
                {source: 76, target: 49, relation: 'cross', value: 3},
                {source: 76, target: 52, relation: 'cross', value: 3},
                {source: 76, target: 71, relation: 'within', value: 3},
                {source: 76, target: 84, relation: 'cross', value: 3},
                {source: 76, target: 89, relation: 'within', value: 3},
                {source: 76, target: 93, relation: 'within', value: 3},
                {source: 76, target: 99, relation: 'cross', value: 3},
                {source: 77, target: 6, relation: 'cross', value: 3},
                {source: 77, target: 17, relation: 'cross', value: 3},
                {source: 77, target: 18, relation: 'within', value: 3},
                {source: 77, target: 28, relation: 'within', value: 3},
                {source: 77, target: 35, relation: 'cross', value: 3},
                {source: 77, target: 36, relation: 'within', value: 3},
                {source: 77, target: 43, relation: 'within', value: 3},
                {source: 77, target: 74, relation: 'cross', value: 3},
                {source: 77, target: 88, relation: 'within', value: 3},
                {source: 77, target: 95, relation: 'cross', value: 3},
                {source: 78, target: 50, relation: 'within', value: 3},
                {source: 78, target: 52, relation: 'cross', value: 3},
                {source: 78, target: 82, relation: 'cross', value: 3},
                {source: 80, target: 50, relation: 'within', value: 3},
                {source: 80, target: 83, relation: 'within', value: 3},
                {source: 82, target: 12, relation: 'cross', value: 3},
                {source: 82, target: 30, relation: 'within', value: 3},
                {source: 82, target: 83, relation: 'cross', value: 3},
                {source: 82, target: 95, relation: 'within', value: 3},
                {source: 82, target: 98, relation: 'cross', value: 3},
                {source: 85, target: 11, relation: 'cross', value: 3},
                {source: 85, target: 22, relation: 'cross', value: 3},
                {source: 85, target: 33, relation: 'cross', value: 3},
                {source: 85, target: 38, relation: 'within', value: 3},
                {source: 85, target: 43, relation: 'cross', value: 3},
                {source: 85, target: 48, relation: 'within', value: 3},
                {source: 85, target: 62, relation: 'cross', value: 3},
                {source: 85, target: 73, relation: 'within', value: 3},
                {source: 85, target: 98, relation: 'cross', value: 3},
                {source: 87, target: 1, relation: 'cross', value: 3},
                {source: 87, target: 10, relation: 'cross', value: 3},
                {source: 87, target: 12, relation: 'cross', value: 3},
                {source: 87, target: 30, relation: 'within', value: 3},
                {source: 87, target: 43, relation: 'cross', value: 3},
                {source: 87, target: 60, relation: 'cross', value: 3},
                {source: 87, target: 88, relation: 'cross', value: 3},
                {source: 87, target: 97, relation: 'within', value: 3},
                {source: 87, target: 98, relation: 'cross', value: 3},
                {source: 88, target: 16, relation: 'cross', value: 3},
                {source: 88, target: 21, relation: 'within', value: 3},
                {source: 88, target: 25, relation: 'cross', value: 3},
                {source: 88, target: 32, relation: 'cross', value: 3},
                {source: 88, target: 44, relation: 'cross', value: 3},
                {source: 88, target: 48, relation: 'cross', value: 3},
                {source: 88, target: 50, relation: 'within', value: 3},
                {source: 88, target: 82, relation: 'cross', value: 3},
                {source: 88, target: 83, relation: 'within', value: 3},
                {source: 88, target: 85, relation: 'cross', value: 3},
                {source: 88, target: 93, relation: 'cross', value: 3},
                {source: 88, target: 94, relation: 'cross', value: 3},
                {source: 88, target: 95, relation: 'cross', value: 3},
                {source: 88, target: 96, relation: 'within', value: 3},
                {source: 91, target: 59, relation: 'within', value: 3},
                {source: 94, target: 28, relation: 'cross', value: 3},
                {source: 94, target: 32, relation: 'cross', value: 3},
                {source: 94, target: 33, relation: 'cross', value: 3},
                {source: 94, target: 35, relation: 'cross', value: 3},
                {source: 94, target: 39, relation: 'cross', value: 3},
                {source: 94, target: 40, relation: 'cross', value: 3},
                {source: 94, target: 50, relation: 'cross', value: 3},
                {source: 94, target: 59, relation: 'cross', value: 3},
                {source: 94, target: 69, relation: 'cross', value: 3},
                {source: 94, target: 74, relation: 'cross', value: 3},
                {source: 94, target: 77, relation: 'cross', value: 3},
                {source: 94, target: 81, relation: 'cross', value: 3},
                {source: 94, target: 87, relation: 'cross', value: 3},
                {source: 94, target: 88, relation: 'cross', value: 3},
                {source: 94, target: 93, relation: 'cross', value: 3},
                {source: 94, target: 96, relation: 'cross', value: 3},
                {source: 94, target: 98, relation: 'cross', value: 3},
                {source: 96, target: 35, relation: 'cross', value: 3},
                {source: 96, target: 41, relation: 'cross', value: 3},
                {source: 96, target: 79, relation: 'within', value: 3},
                {source: 96, target: 92, relation: 'cross', value: 3},
                {source: 97, target: 6, relation: 'cross', value: 3},
                {source: 97, target: 18, relation: 'cross', value: 3},
                {source: 97, target: 21, relation: 'cross', value: 3},
                {source: 97, target: 59, relation: 'cross', value: 3},
                {source: 97, target: 61, relation: 'cross', value: 3},
                {source: 97, target: 69, relation: 'within', value: 3},
                {source: 97, target: 71, relation: 'within', value: 3},
                {source: 97, target: 73, relation: 'within', value: 3},
                {source: 97, target: 82, relation: 'within', value: 3},
                {source: 99, target: 1, relation: 'within', value: 3},
                {source: 99, target: 28, relation: 'within', value: 3},
                {source: 99, target: 33, relation: 'cross', value: 3},
                {source: 99, target: 42, relation: 'cross', value: 3},
                {source: 99, target: 52, relation: 'cross', value: 3},
                {source: 99, target: 83, relation: 'within', value: 3},
            ]
        }


        return (
            <div className="gutter-example simple-force-chart-demo">
                <Row gutter={10}>
                    <Col className="gutter-row" md={24}>
                        <div className="gutter-box">
                            <Card title="部分高链接度社区可视化结果" bordered={false}>
                                <D3SimpleForceChart data={data}/>
                            </Card>
                        </div>
                    </Col>
                </Row>
            </div>
        )
    }
}

export default SimpleForceChart2
